### ISSUE TITLE
后端服务器是否一定要支持https

### ISSUE THREAD

**Issue by Yuanmu93** [chenguanyou/weixin_YiQi#3]
你好，我在在阿里云部署了后端代码，login方法报400错误，显示是“{"non_field_errors":["无法使用提供的认证信息登录。"]}”，服务器的访问方式是http，不是https，是否是这个原因还是什么原因导致的，谢谢！

![image](https://user-images.githubusercontent.com/20705403/49580090-12708580-f989-11e8-9b94-bd794bbca6c6.png)

**Comment by chenguanyou** [comment]
字符编码的问题，谢谢反馈，我会修复下！
